### PR TITLE
Update recovering-files-from-snapshots.md

### PR DESCRIPTION
**Pull request by ShiraFeldman**
Changed 1 instance of NCAR to NSF NCAR, did not change others because in code or technical language

### CODE REVIEW

**Comment by ShiraFeldman** [comment]
Hi Ben, are you back? If so, welcome back! I hope you are feeling well!

I am not sure what this means about merging into main, can you help me out?

Best,
Shira

**Comment by dphow** [comment]
Hi Shira,

This simply means that the changes under issue
https://github.com/NCAR/HPC-Docs/pull/210 is now incorporated into the
`main` branch, where the documentation gets published from. Once changes
are made to documentation as you have been doing, they are essentially
staged into what are called commits, or pending changes to the content.

After being reviewed and passing checks for any errors, then the commits
can then be approved to merge into `main`, also known as a pull request. I
believe you plus all of CSG has authority to approve these merges. Only
after merging will the updates made actually show up on the live NCAR HPC
Docs pages, in less than an hour or so.


Hope that makes sense!

*Daniel Howard *- he/him/his
NSF <https://www.nsf.gov/> NCAR <https://ncar.ucar.edu/> Computational &
Information Services Laboratory (CISL <https://www2.cisl.ucar.edu/>)
HPC Consultant, Consulting Services Group (CSG
<https://staff.ucar.edu/browse/orgs/HPCDSEC>)
Office: Mesa Lab, Room 55G
<https://www.linkedin.com/in/dphoward>         Personal Website
<http://dphow.github.io/>          My Calendar:
<https://calendar.google.com/calendar/embed?src=dhoward%40ucar.edu&ctz=America%2FDenver>

You may schedule a virtual meeting on my calendar here
<https://app.squarespacescheduling.com/schedule.php?owner=26907589&calendarID=7319807>
Learn about NCAR HPC support and submit requests to the Help Desk here
<https://arc.ucar.edu/knowledge_base/74318011>

**Comment by ShiraFeldman** [comment]
Thank you!

**Comment by benkirk** [comment]
Thanks for the summary Daniel, spot on!

I’m ‘easing’ back this week, pun intended. I’ll fill everyone available in
at tomorrow’s group meeting!

**Pull request merged**
